[package]
name = "searust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8.16"
serde_json = "1.0.105"
clap = { version = "4.4.2", features = ["derive"] }
tiny_http = "0.11"

